### ISSUE TITLE
Performance problem on adding properties with cardinality list.

### ISSUE THREAD

**Issue by ml86** [ShiftLeftSecurity/overflowdb-codegen#9]
We use the very inefficient ":+" operation when adding node properties of list cardinality.
Here is the code position I mean: https://github.com/ShiftLeftSecurity/overflowdb-codegen/blob/a334b4c11b232fd5a72846e3a191eca11b8a724c/src/main/scala/overflowdb/codegen/Helpers.scala#L94

This operation alone takes 6 minutes to add properties on IOFlow nodes for a 12 min cpg2sp run for a customer jar. I strongly suggest adding the new property at the beginning or using a different data structure.

**Comment by mpollmeier** [comment]
Is the workaround in https://github.com/ShiftLeftSecurity/codepropertygraph/pull/730/ sufficient for now, or should I resolve this as well? 
As you know we're moving away from the tinkerpop api, but it's a slow process with many interruptions.

**Comment by ml86** [comment]
I does not have high priority but since we most likely will have the updateSpecificProperty method in our interface for quite some more times, we should fix this if it is not a big change.

**Comment by mpollmeier** [comment]
closing: we don't use Cardinality.list any more. 
n.b. the codegen still generates this code, but that'll go out shortly as well.
